### ISSUE TITLE
Different output on local and production

### ISSUE THREAD

**Issue by udewilde** [jstejada/react-typist#33]
I have been using the module on my local machine and everything works perfectly. 
However, when I moved to production, Typist.Backspace & Typist.Delay have completely stopped working. 
I mean that the text will just be added to the previous one, without any rythme change.
The output is just one big string
```
<Typist onCharacterTyped={this.someFunction} avgTypingDelay={150} startDelay={1000} >
    FOO
    <Typist.Backspace count={30} delay={3000}/>
    <Typist.Delay ms={3000} />
    BAR
</Typist>

//FOOBAR
```
If it can be any indicator, I noticed that on localhost when the `Typist.Backspace` occurs, this happens:

 ```
someFunction = (char, charIndex) => {
  console.log(char) // BACK (+ a right arrow on top)
};
```
But nothing is logged when in production.

Any idea what I am getting wrong? 

Thanks

**Comment by elliotleelewis** [comment]
I have the exact same issue!

**Comment by jstejada** [comment]
Ah, that's no good! What version are you running?

**Comment by jstejada** [comment]
Also, how are you deploying to production?

**Comment by udewilde** [comment]
I'm running version 2.0.1
The app is hosted on firebase, so I am deploying to production with the `firebase deploy`  command, with a react-create-app structure

**Comment by jstejada** [comment]
Ah, that's no good! Do you mind giving me the following information:
- react-typist version (in your package.json)
- react version (in your package.json)
- if you are able to share, a description of your build process to production
- if you are able to share, the site you deployed to which isn't working
- any other info that might be useful to reproduce this scenario

Thank you!

**Comment by jstejada** [comment]
Thanks @udewilde! Do you mean [create-react-app](https://github.com/facebookincubator/create-react-app)?

Do you know which versions of `create-react-app`,  and `react-scripts` (should be in your package.json) you are using?

Thank you!

**Comment by udewilde** [comment]
Sure! here are the relevant elements in my package.json

```
"dependencies": {
    "firebase": "^3.7.8",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-typist": "^2.0.1",
  },
  "devDependencies": {
    "react-scripts": "0.9.5",
    "sw-precache": "^5.2.0",
    "sw-precache-webpack-plugin": "^0.11.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build && cp manifest.json build/ && sw-precache --root='build/' --static-file-globs='build/**/!(*map*)'",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
```

The build process is using the one described in the [create-react-app](https://github.com/facebookincubator/create-react-app), with a pre-cache addition to it.

[Here](https://laloc.fr/) is the link to the website. If you open the Chrome Devtools, you should see every char change logged in the console, as well as the char index. 
In this instance, I am not displaying the `<Typist>` component, but I am using `onCharacterTyped` to update the state feeding the search bar placeholder. 
However I've tried not updating any state whatsoever and just rendering the `<Typist>` component, but the output was the same.

**Comment by jstejada** [comment]
Awesome, thank you for all the info! :) This should help me reproduce and get to the bottom og this. I'll dive into this later this evening or tomorrow

Thanks again!

**Comment by elliotleelewis** [comment]
I'm using [Laravel Mix](https://github.com/JeffreyWay/laravel-mix), not create-react-app, so I don't think that this is solely related to create-react-app

**Comment by jstejada** [comment]
thanks for the info @elliotleelewis. which version of react are you using?

**Comment by jstejada** [comment]
thanks @elliotleelewis, @udewilde. I think I figured out what's going on, when the code is minified, this check no longer works: https://github.com/jstejada/react-typist/blob/master/src/utils.js#L42 because the `Backspace` Component is no longer called `Backspace`.

I'll push a fix soon

**Comment by jstejada** [comment]
I've released a fix with v2.0.3 (d122bd1), which should resolve your issue.

Let me know if that's not the case!

**Comment by udewilde** [comment]
Hey @jstejada, I have just updated the module (`2.0.3`) , but I still get the same issue in production.  
It's a new build and new push to production, so it is definitely not the old version running.
I have left the code with the issue in [production](https://laloc.fr/), so you can see the output in the search bar placeholder.

**Comment by elliotleelewis** [comment]
Yeah I still have same issue too!

**Comment by jstejada** [comment]
Oh, yeah you're right! Sorry, that was my bad! It should be fixed in 2.0.4! @elliotleelewis @udewilde

**Comment by elliotleelewis** [comment]
Works for me 😃

**Comment by udewilde** [comment]
Works for me too! 
Thanks
